### ISSUE TITLE
composerrel való telepítés

### ISSUE THREAD

**Issue by lokutus24** [Shoprenter/api-client#1]
Üdv!

Hogy lehet feltelepíteni Laravel környezetben? Mivel nincs composer parancs bemásoltam a vendor mappába majd egy controlleren belül használtam a use ShopRenter\ApiCall; -t, de meghívásnál nem látja az osztályt. Class 'ShopRenter\ApiCall' not found 

Üdv
Gábor

**Comment by lokutus24** [comment]
Sikerült!

Fő composerhez hozzá kellett adni:

"require": { "shoprenter/api-client" : "dev-master" }
"repositories": [
        {
            "url": "https://github.com/Shoprenter/api-client.git",
            "type": "git"
        }
    ]
Így feltelepítette és látja a controller is.

**Comment by norberttinnonic** [comment]
Szia,
örülök neki, hogy megoldódott!
További jó munkát!
